services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
    volumes:
       - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
    postgres_data: